name: panaroo-CI

on:
  push:
    branches:
  pull_request:
    branches:
  schedule:
    - cron:  '1 1 1 * *'


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cd-hit
        sudo apt-get install mafft
        wget https://github.com/marbl/Mash/releases/download/v2.2/mash-Linux64-v2.2.tar
        tar -xvf mash-Linux64-v2.2.tar
        sudo cp ./mash-Linux64-v2.2/mash /usr/bin/mash
        python --version
        pip install -U pip
        pip install -U pytest
        wget https://github.com/gtonkinhill/panaroo_test_data/releases/download/v0.0.2/travis_test_data.zip
        unzip travis_test_data.zip
        
    - name: Install
      run: pip install .

<<<<<<< HEAD

    - name: Clean Panaroo alignment resume state
      run: |
          rm -f "${{ github.workspace }}/travis_test_data/alignment_resume_state.json"
          rm -rf "${{ github.workspace }}/travis_test_data/aligned_gene_sequences"
          rm -rf "${{ github.workspace }}/travis_test_data/aligned_protein_sequences"
          rm -rf "${{ github.workspace }}/travis_test_data/unaligned_dna_sequences"
          rm -f "${{ github.workspace }}/travis_test_data/core_gene_alignment.aln"
          rm -f "${{ github.workspace }}/travis_test_data/core_gene_alignment_filtered.aln"
          rm -f "${{ github.workspace }}/travis_test_data/core_alignment_header.embl"
          rm -f "${{ github.workspace }}/travis_test_data/core_alignment_filtered_header.embl"
          rm -f "${{ github.workspace }}/travis_test_data/alignment_entropy.csv"

    - name: Validation Tests
      run: pytest -W ignore -q --datafolder="${{ github.workspace }}/travis_test_data/"

=======
    - name: Validation Tests Except MSA
      run: pytest -W ignore -q --ignore=tests/test_msa.py --datafolder="${{ github.workspace }}/travis_test_data/"

    - name: Clean Panaroo alignment outputs
      run: |
          rm -f "${{ github.workspace }}/travis_test_data/alignment_resume_state.json"
          rm -rf "${{ github.workspace }}/travis_test_data/aligned_gene_sequences"
          rm -rf "${{ github.workspace }}/travis_test_data/aligned_protein_sequences"
          rm -rf "${{ github.workspace }}/travis_test_data/unaligned_dna_sequences"
          rm -f "${{ github.workspace }}/travis_test_data/core_gene_alignment.aln"
          rm -f "${{ github.workspace }}/travis_test_data/core_gene_alignment_filtered.aln"
          rm -f "${{ github.workspace }}/travis_test_data/core_alignment_header.embl"
          rm -f "${{ github.workspace }}/travis_test_data/core_alignment_filtered_header.embl"
          rm -f "${{ github.workspace }}/travis_test_data/alignment_entropy.csv"

    - name: Validation MSA Test
      run: pytest -W ignore -q tests/test_msa.py --datafolder="${{ github.workspace }}/travis_test_data/"

>>>>>>> 32b1ce5 (MSA test separately)
